env:  # 推理环境设置
  inference_env: real  # 选仿真还是真机 option: sim/real
  platform_type: "5w"  # 机器人型号 option: "4pro"/"5"/"5w"
  5w_wholebody: false  # 仅5w生效；在 observation.state/action 末尾追加并控制4维下半身
  5w_base_move: false  # 仅5w生效；从 action 末尾读取 [vx, vy, vyaw] 并发布 /cmd_vel
  5w_lowerlock: [0, 0, 0, 0]  # 全身模式下按 /lb_leg_traj index 锁定；1 会锁定对应关节并使用 go_bag_path 首帧值，0 正常运动。仅动最后一个设为 [1,1,1,0]；
  which_arm: both  # 控制左手、右手还是双手 option: both/left/right
  eef_type: qiangnao  # 夹爪或手型类型  option: leju_claw/qiangnao/sg100/rq2f85(仿真)
  ros_rate: 10  # 推理频率
  direct_to_wbc: false  # 是否使用direct to wbc模式。
  enable_action_interpolation: true
  control_rate: 100  # WBC插值后的实际控制指令频率
  image_size: [848, 480]  # 相机缩放尺寸 option: [640, 480](仿真)/[848, 480](真机）
  camera_encoding: h265  # 相机编码格式: "jpeg" 或 "h265"。h265 时自动订阅 H265 stream topic 并进行实时解码。
  

inference:  # 推理和评测设置
  go_bag_path: null    # bag 回放路径
  policy_type: client  # 要加载的模型类型,外挂模式选择client, 选择client模式后下面的pretrained_path失去作用
  pretrained_path: /path/to/checkpoint  # 要加载的权重路径。
  eval_episodes: 10  # 评测跑多少条
  max_episode_steps: 200  # 每条最多跑多少步
  task_prompt: "Pick and Place"

  async_inference: false
  rtc_lite_enabled: false  # 是否启用 RTC-Lite 队列合并。
  rtc_full_enabled: false  # 模型空间 RTC；启用时必须关闭 rtc_lite_enabled。
  rtc_full_mode: vjp  # 可选 vjp / inpainting。
